### PR TITLE
First KD Draft (Don't Merge Right Away)

### PR DESCRIPTION
**Pull request by QiyouChang**
First draft of Knowledge Distillation for ModelB with following changes:
1. Full implementation of KD. 
2. Modify file names for easy access 
3. Modify some imports for future easy access 
4. Make files generalizable

### CODE REVIEW

**Comment by baolef** [comment]
there are a lot of pycache files that should not be committed.

**Review by baolef — CHANGES_REQUESTED** [review]
the pyc files need to be removed

**Comment by QiyouChang** [comment]
But this is exactly what I did. In the commit, you can see all pyc file has a red dash mark to the right denoting that the file is removed/deleted in the current commit (we used to have pyc file in the main branch.)

**Comment by baolef** [comment]
sorry, didin't notice

**Review by baolef — APPROVED** [review]
lgtm

**Pull request merged**
